### ISSUE TITLE
Anchor placeholder in breadcrumbs

### ISSUE THREAD

**Issue by peterblazejewicz** [mdo/mdoml#5]
I think placeholder anchor can be used breadcrumb component, right? 

``` html
<breadcrumb>
  <a href="#">Home</a>
  <a href="#">Subfolder</a>
  <a href="#">Subfolder</a>
  <a>Page</a>
</breadcrumb>
```

Still a way clearer then current #Bootstrap: http://getbootstrap.com/components/#breadcrumbs
Let me know if I could do PR,
Thanks!

**Comment by mdo** [comment]
Yeah, I imagine so.
